server:
  port: 8018
  display-name: TEST
  jsp-servlet:
      init-parameters:
        development: true

#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
#    date-format: yyyy-MM-dd HH:mm:ss


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  tomcat:
    max-http-post-size: 10

file:
  upload:
    url: E:/test1/src/main/webapp/upload


spring:
  profiles:
    include: devdb
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.100.104
    port: 5672
    username: admin
    password: admin

logging:
#  config: classpath:log4j2.xml
#  path: logs
  level:
      org:
        hibernate:
          SQL: DEBUG
#          format_sql: true




